import json

def patch_file():
    with open('backend/src/prompts/nlu.prompt.ts', 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Update the schema
    content = content.replace(
        '"complexity_hints": [<strings from user input suggesting job difficulty>],\n    "additional_details": "<any extra info or null>"\n  },\n  "requires_clarification": <true|false>,',
        '"complexity_hints": [<strings from user input suggesting job difficulty>],\n    "additional_details": "<any extra info or null>",\n    "job_complexity": "<basic|intermediate|complex|null>"\n  },\n  "normalized": "<clean English/Roman Urdu summary>",\n  "requires_clarification": <true|false>,'
    )

    # 2. Update the examples
    replacements = [
        ('{"confidence":0.95,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"ac_repair","location":{"area":"G-13","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TOMORROW","slot":"morning","flexible":false,"raw_text":"kal subah"},"budget":{"sensitivity":"high","max_amount":null,"raw_text":"budget zyada nahi hai"},"complexity_hints":["bilkul kaam nahi kar raha"],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.95,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"ac_repair","location":{"area":"G-13","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TOMORROW","slot":"morning","flexible":false,"raw_text":"kal subah"},"budget":{"sensitivity":"high","max_amount":null,"raw_text":"budget zyada nahi hai"},"complexity_hints":["bilkul kaam nahi kar raha"],"additional_details":null,"job_complexity":"intermediate"},"normalized":"AC repair needed","requires_clarification":false,"clarification_question":null}'),
        
        ('{"confidence":0.97,"language_detected":"english","intent":"book_service","entities":{"service_type":"plumber","location":{"area":"F-10","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TODAY","slot":"evening","flexible":false,"raw_text":"today evening"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["kitchen pipe is leaking badly"],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.97,"language_detected":"english","intent":"book_service","entities":{"service_type":"plumber","location":{"area":"F-10","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TODAY","slot":"evening","flexible":false,"raw_text":"today evening"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["kitchen pipe is leaking badly"],"additional_details":null,"job_complexity":"intermediate"},"normalized":"Plumbing repair needed","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.94,"language_detected":"roman_urdu_mixed","intent":"book_service","entities":{"service_type":"electrician","location":{"area":"F-8","city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"high","max_amount":2000,"raw_text":"budget 2000 tak"},"complexity_hints":["switch board change karna hai"],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.94,"language_detected":"roman_urdu_mixed","intent":"book_service","entities":{"service_type":"electrician","location":{"area":"F-8","city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"high","max_amount":2000,"raw_text":"budget 2000 tak"},"complexity_hints":["switch board change karna hai"],"additional_details":null,"job_complexity":"basic"},"normalized":"Electrical work needed","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.88,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"plumber","location":{"area":"G-13","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TODAY","slot":null,"flexible":false,"raw_text":"jaldi"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["pani aara hai har jagah"],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.88,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"plumber","location":{"area":"G-13","city":"Islamabad","coordinates":null},"urgency":"high","preferred_time":{"date":"TODAY","slot":null,"flexible":false,"raw_text":"jaldi"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["pani aara hai har jagah"],"additional_details":null,"job_complexity":"intermediate"},"normalized":"Plumbing emergency","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.25,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null},"requires_clarification":true,"clarification_question":"Kya kaam karwana hai? Plumber, electrician, AC repair, ya koi aur service?"}',
         '{"confidence":0.25,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null,"job_complexity":null},"normalized":"General service request","requires_clarification":true,"clarification_question":"Kya kaam karwana hai? Plumber, electrician, AC repair, ya koi aur service?"}'),

        ('{"confidence":0.98,"language_detected":"roman_urdu","intent":"greeting","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.98,"language_detected":"roman_urdu","intent":"greeting","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null,"job_complexity":null},"normalized":"Greeting","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.92,"language_detected":"roman_urdu","intent":"check_status","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.92,"language_detected":"roman_urdu","intent":"check_status","entities":{"service_type":null,"location":{"area":null,"city":"Islamabad","coordinates":null},"urgency":"medium","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":[],"additional_details":null,"job_complexity":null},"normalized":"Check booking status","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.93,"language_detected":"urdu","intent":"book_service","entities":{"service_type":"ac_repair","location":{"area":"G-11","city":"Islamabad","coordinates":null},"urgency":"emergency","preferred_time":{"date":"TODAY","slot":null,"flexible":false,"raw_text":"فوری طور پر"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["بالکل ٹھنڈا نہیں کر رہا"],"additional_details":null},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.93,"language_detected":"urdu","intent":"book_service","entities":{"service_type":"ac_repair","location":{"area":"G-11","city":"Islamabad","coordinates":null},"urgency":"emergency","preferred_time":{"date":"TODAY","slot":null,"flexible":false,"raw_text":"فوری طور پر"},"budget":{"sensitivity":"medium","max_amount":null,"raw_text":null},"complexity_hints":["بالکل ٹھنڈا نہیں کر رہا"],"additional_details":null,"job_complexity":"intermediate"},"normalized":"Emergency AC repair needed","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.93,"language_detected":"roman_urdu_mixed","intent":"book_service","entities":{"service_type":"tutor","location":{"area":"I-8","city":"Islamabad","coordinates":null},"urgency":"low","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":15000,"raw_text":"budget 15000 monthly"},"complexity_hints":["math ki tuition"],"additional_details":"Monthly tuition for daughter"},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.93,"language_detected":"roman_urdu_mixed","intent":"book_service","entities":{"service_type":"tutor","location":{"area":"I-8","city":"Islamabad","coordinates":null},"urgency":"low","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":null},"budget":{"sensitivity":"medium","max_amount":15000,"raw_text":"budget 15000 monthly"},"complexity_hints":["math ki tuition"],"additional_details":"Monthly tuition for daughter","job_complexity":"basic"},"normalized":"Math tutoring needed","requires_clarification":false,"clarification_question":null}'),

        ('{"confidence":0.91,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"carpenter","location":{"area":"F-10","city":"Islamabad","coordinates":null},"urgency":"low","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":"agle hafte"},"budget":{"sensitivity":"medium","max_amount":30000,"raw_text":"budget 25-30 hazar"},"complexity_hints":["almari banana hai custom size ki","achi quality ka wood chahiye"],"additional_details":"Custom wardrobe, wants good quality wood"},"requires_clarification":false,"clarification_question":null}',
         '{"confidence":0.91,"language_detected":"roman_urdu","intent":"book_service","entities":{"service_type":"carpenter","location":{"area":"F-10","city":"Islamabad","coordinates":null},"urgency":"low","preferred_time":{"date":null,"slot":null,"flexible":true,"raw_text":"agle hafte"},"budget":{"sensitivity":"medium","max_amount":30000,"raw_text":"budget 25-30 hazar"},"complexity_hints":["almari banana hai custom size ki","achi quality ka wood chahiye"],"additional_details":"Custom wardrobe, wants good quality wood","job_complexity":"complex"},"normalized":"Custom wardrobe construction","requires_clarification":false,"clarification_question":null}')
    ]

    for old, new in replacements:
        content = content.replace(old, new)
        
    with open('backend/src/prompts/nlu.prompt.ts', 'w', encoding='utf-8') as f:
        f.write(content)

if __name__ == "__main__":
    patch_file()
